### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by CoreProduction** [CoreElectronics/CE-Arducam-MicroPython#1]
[PEP 8](https://peps.python.org/pep-0008/#function-and-variable-names) indicates a naming convention for `lowercase_variables_with_underscore_separation` rather than `camelCaseNames`. Since this is a new project with no prevailing history of using `camelCase` can we update this module to use `lowercase_variables_with_underscore` eg
- `get_sensor_config` 
- rather than `getSensorConfig`

**Comment by CoreProduction4** [comment]
Thanks for the PR @CoreProduction, commit [44d5042](https://github.com/CoreElectronics/CE-Arducam-MicroPython/commit/44d5042dc7bbb19f179c98f469df875dea7b3434) has fixed camelCase and a couple other naming discrepancies.
