### ISSUE TITLE
Setting regs to configure camera

### ISSUE THREAD

**Issue by nadalini103** [CoreElectronics/CE-Arducam-MicroPython#3]
Hi,
First, wanted to congratulate Liam for the nice work!!
I tried the driver and was able to take a picture with the code provided. Then, I started setting the registers shown in the Arducam repository to configure the camera, just like it was implemented with the setCameraFilter function and the image resolution. However, when trying to set more than one register to configure multiple image parameters, only the last setting was implemented. Have you tried to set multiple image parameters? 
I added the following lines to the code:
(On the begining of the camera class)
    CAM_REG_BRIGHTNESS_CONTROL                 = 0X22
    CAM_REG_CONTRAST_CONTROL                   = 0X23

(On the capture_JPG function):
        self._write_reg(camera.CAM_REG_BRIGHTNESS_CONTROL, 0x02) 
        self._wait_idle()
        self._write_reg(camera.CAM_REG_CONTRAST_CONTROL, 0x04) 
        self._wait_idle()

**Comment by CoreProduction4** [comment]
Hi nadalini,

Thank you!

I havent had a chance to come back for a wholistic test for the driver just yet. It might be worth loading up the ArduCam MEGA demo to see if this behaviour is consistent with the current state of the micropython driver.

Best of luck! Would love to hear how you go!

**Comment by CoreProduction4** [comment]
Hi nadalini,

I just implemented the contrast and brightness functions - so am able to test now!

Using the following code I could still get `set_brightness_level` to run (the contrast levels are hard to tell the difference)

```
spi = SPI(0,sck=Pin(18), miso=Pin(16), mosi=Pin(19), baudrate=8000000)
cs = Pin(17, Pin.OUT)

# button = Pin(15, Pin.IN,Pin.PULL_UP)
onboard_LED = Pin(25, Pin.OUT)

cam = Camera(spi, cs)

cam.resolution = '640x480'
# cam.set_filter(cam.SPECIAL_REVERSE)
cam.set_brightness_level(cam.BRIGHTNESS_PLUS_4)
cam.set_contrast(cam.CONTRAST_MINUS_3)


onboard_LED.on()
cam.capture_jpg()
sleep_ms(50)
cam.saveJPG('image.jpg')
onboard_LED.off()
```

If you have some example photos I'd love to see the changes when layering the filters!
