### ISSUE TITLE
Will it drive the 3MP as well?

### ISSUE THREAD

**Issue by felixmosh** [CoreElectronics/CE-Arducam-MicroPython#4]
First of all, thank you for this driver 🙏🏼
https://www.arducam.com/product/presale-mega-3mp-color-rolling-shutter-camera-module-with-solid-camera-case-for-any-microcontroller/

**Comment by CoreProduction4** [comment]
Hi Felix,

Sorry for the delay in getting back to you!

It does do some basic driving of the 3MP but you have to keep the shutter open for a little while before capturing clear photos, see: https://forum.arducam.com/t/mega-3mp-micropython-driver/5708

**Comment by CoreProduction4** [comment]
Hi Felix,

The latest release has been tested and confirmed to be working with the 3MP as well.
![image](https://github.com/CoreElectronics/CE-Arducam-MicroPython/assets/138748235/966483fc-6fc8-4936-b85b-fdc172c146fc)
(Taken on the 3MP using the following release: https://github.com/CoreElectronics/CE-Arducam-MicroPython/commit/656cab687c30034fd7f62948d3708e79e0dc40cd)

Happy making!

**Comment by CoreProduction4** [comment]
Closing topic and updating README
