### ISSUE TITLE
Question about camera library

### ISSUE THREAD

**Issue by jimtal001** [CoreElectronics/CE-Arducam-MicroPython#6]
In the examples folder of your code repository you have the single_photo.py code which imports the camera library but I'm not able to locate this library in your code repository.  Is it available?  Where to get it?  Thanks Jim

**Comment by CoreProduction4** [comment]
Hi Jim,

The camera library can be generated by copying the 'camera' class from the `main.py` file in the head of the directory.
This is so that all Makers can quickly iterate on the library and complete the TODO List.

I'll add a note in the README!

**Comment by jimtal001** [comment]
Thanks
