### ISSUE TITLE
camera question

### ISSUE THREAD

**Issue by jimtal001** [CoreElectronics/CE-Arducam-MicroPython#7]
Can you confirm that the camera listed below will work with your library:
**Arducam Mini 2MP Plus** – OV2640 SPI Camera Module 
https://www.arducam.com/product/arducam-2mp-spi-camera-b0067-arduino/

If not can you suggest the model with 3MP which has been tested.  Thanks!

**Comment by CoreProduction4** [comment]
Hi jimtal001,

This driver is just for the Arducam MEGA cameras:
https://core-electronics.com.au/arducam-mega-3mp-camera.html
https://core-electronics.com.au/arducam-mega-5mp-camera.html

The OV2640 uses both I2C and SPI so wont work, though there is extensive documentation for the Arduino driver so a port might be possible!
